defaults: &defaults
  adapter: mysql
  encoding: utf8
  reconnect: false
  pool: 5
  username: clahrc
  socket: /opt/local/var/run/mysql5/mysqld.sock

development:
  <<: *defaults
  database: clahrc_development

test:
  <<: *defaults
  database: clahrc_test
  